---

- name: Copy nginx conf template
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    backup: yes
    owner: nginx
    group: nginx

- name: start nginx
  systemd:
    name: nginx
    state: restarted
